// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class BasicType
{
    public long Id { get; set; }

    public long IdLocation { get; set; }

    public long IdMaterial { get; set; }

    public string? SpsCode { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public bool MixedFlag { get; set; }

    public virtual ICollection<AdditionalBasicType> AdditionalBasicType { get; set; } = new List<AdditionalBasicType>();

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual Material IdMaterialNavigation { get; set; } = null!;

    public virtual ICollection<LoadorderSilo> LoadorderSilo { get; set; } = new List<LoadorderSilo>();

    public virtual ICollection<MappingBasicType> MappingBasicTypeIdBasicTypeNavigation { get; set; } = new List<MappingBasicType>();

    public virtual ICollection<MappingBasicType> MappingBasicTypeIdOtherTypeNavigation { get; set; } = new List<MappingBasicType>();

    public virtual ICollection<Silo> Silo { get; set; } = new List<Silo>();
}