// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Beladungen
{
    public int? BelaId { get; set; }

    public string? WerkNr { get; set; }

    public string? BeinNr { get; set; }

    public string? Status { get; set; }

    public decimal? Sollmenge { get; set; }

    public decimal? Istmenge { get; set; }

    public string? GewichtEinheit { get; set; }

    public decimal? TaraGewicht { get; set; }

    public decimal? BruttoGewicht { get; set; }

    public int? TaraGewichtId { get; set; }

    public int? BruttoGewichtId { get; set; }

    public decimal? NettoGewicht { get; set; }
}