// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Carrier
{
    public long Id { get; set; }

    public string Name { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long IdLocation { get; set; }

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual ICollection<MappingCarrierDebitor> MappingCarrierDebitor { get; set; } = new List<MappingCarrierDebitor>();

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}