// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class ConfigMessage
{
    public long Id { get; set; }

    public long? IdMessageDispatcher { get; set; }

    public long IdLocation { get; set; }

    public string Name { get; set; } = null!;

    public int Cause { get; set; }

    public int DelayMinutes { get; set; }

    public string? Subject { get; set; }

    public string? Content { get; set; }

    public string? Condition { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<ConfigMessagesDocument> ConfigMessagesDocument { get; set; } = new List<ConfigMessagesDocument>();

    public virtual ICollection<DeliveryMessage> DeliveryMessage { get; set; } = new List<DeliveryMessage>();

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual MessageDispatcher? IdMessageDispatcherNavigation { get; set; }
}