// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class ConfigPlantSalesOrg
{
    public long Id { get; set; }

    public long IdPlant { get; set; }

    public long IdLogo { get; set; }

    public string ReferenzDeliveryForm { get; set; } = null!;

    public string ReferenzLoadingForm { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long? IdSalesOrganization { get; set; }

    public virtual Logo IdLogoNavigation { get; set; } = null!;

    public virtual Plant IdPlantNavigation { get; set; } = null!;

    public virtual SalesOrganization? IdSalesOrganizationNavigation { get; set; }
}