// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class ConfigPlantMaterial
{
    public long Id { get; set; }

    public long IdPlant { get; set; }

    public long IdMaterial { get; set; }

    public decimal BatchObligation { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long IdProductgroup { get; set; }

    public virtual ICollection<Batch> Batch { get; set; } = new List<Batch>();

    public virtual ICollection<ConfigSeal> ConfigSeal { get; set; } = new List<ConfigSeal>();

    public virtual Material IdMaterialNavigation { get; set; } = null!;

    public virtual Plant IdPlantNavigation { get; set; } = null!;

    public virtual Productgroup IdProductgroupNavigation { get; set; } = null!;

    public virtual ICollection<OdcAdjustmentQuantity> OdcAdjustmentQuantity { get; set; } = new List<OdcAdjustmentQuantity>();
}