// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class ConfigSeal
{
    public long Id { get; set; }

    public long IdPlant { get; set; }

    public long? IdSeal { get; set; }

    public int Kind { get; set; }

    public int Position { get; set; }

    public int Width { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long? IdProductgroup { get; set; }

    public long? IdConfigPlantMaterial { get; set; }

    public virtual ConfigPlantMaterial? IdConfigPlantMaterialNavigation { get; set; }

    public virtual Plant IdPlantNavigation { get; set; } = null!;

    public virtual Productgroup? IdProductgroupNavigation { get; set; }

    public virtual Seal? IdSealNavigation { get; set; }
}