// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Country
{
    public long Id { get; set; }

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public bool Eu { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<CustomerAgreement> CustomerAgreement { get; set; } = new List<CustomerAgreement>();

    public virtual ICollection<Debitor> Debitor { get; set; } = new List<Debitor>();

    public virtual ICollection<DeliveryOrderDebitor> DeliveryOrderDebitor { get; set; } = new List<DeliveryOrderDebitor>();

    public virtual ICollection<OrderDebitor> OrderDebitor { get; set; } = new List<OrderDebitor>();
}