// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class CustomerAgreement
{
    public long Id { get; set; }

    public long IdLocation { get; set; }

    public long? IdPlant { get; set; }

    public long? IdCountry { get; set; }

    public long? IdMaterial { get; set; }

    public int PackagingType { get; set; }

    public int TransportType { get; set; }

    public bool FlagGoodsRecipient { get; set; }

    public bool FlagInvoiceRecipient { get; set; }

    public bool FlagCarrier { get; set; }

    public bool Active { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public long IdCategory { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long? IdDebitor { get; set; }

    public virtual ICollection<CustomerAgrParameter> CustomerAgrParameter { get; set; } = new List<CustomerAgrParameter>();

    public virtual TypeAgreementCategory IdCategoryNavigation { get; set; } = null!;

    public virtual Country? IdCountryNavigation { get; set; }

    public virtual Debitor? IdDebitorNavigation { get; set; }

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual Material? IdMaterialNavigation { get; set; }

    public virtual Plant? IdPlantNavigation { get; set; }
}