// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Debitor
{
    public long Id { get; set; }

    public string Name1 { get; set; } = null!;

    public string? Name2 { get; set; }

    public string? Name3 { get; set; }

    public string Street { get; set; } = null!;

    public string? Housenumber { get; set; }

    public string? Postcode { get; set; }

    public string? Location { get; set; }

    public string? Phone { get; set; }

    public string? Language { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public bool? Active { get; set; }

    public long IdCountry { get; set; }

    public long DebitorNumber { get; set; }

    public virtual ICollection<Contingent> Contingent { get; set; } = new List<Contingent>();

    public virtual ICollection<CustomerAgreement> CustomerAgreement { get; set; } = new List<CustomerAgreement>();

    public virtual Country IdCountryNavigation { get; set; } = null!;

    public virtual ICollection<IdentificationCard> IdentificationCard { get; set; } = new List<IdentificationCard>();

    public virtual ICollection<MappingSoDebitor> MappingSoDebitor { get; set; } = new List<MappingSoDebitor>();
}