// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class DeliveryPosition
{
    public long Id { get; set; }

    public long IdDeliveryHead { get; set; }

    public bool Active { get; set; }

    public decimal LoadedQuantity { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public int PositionNumber { get; set; }

    public virtual DeliveryOrderPosition? DeliveryOrderPosition { get; set; }

    public virtual DeliveryHead IdDeliveryHeadNavigation { get; set; } = null!;
}