// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class DeliveryDocument
{
    public long Id { get; set; }

    public long IdDeliveryHead { get; set; }

    public int DocuType { get; set; }

    public byte[]? Content { get; set; }

    public string? Extension { get; set; }

    public DateTime? Timestamp { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long? IdDeliveryMessage { get; set; }

    public string? DocuCode { get; set; }

    public virtual DeliveryHead IdDeliveryHeadNavigation { get; set; } = null!;

    public virtual DeliveryMessage? IdDeliveryMessageNavigation { get; set; }
}