// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Device
{
    public long Id { get; set; }

    public long IdLocation { get; set; }

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string ModuleCode { get; set; } = null!;

    public int PackagingType { get; set; }

    public int TransportType { get; set; }

    public string? Paramstring { get; set; }

    public int DeviceType { get; set; }

    public int Porttype { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public int Roles { get; set; }

    public virtual ICollection<DeviceParameter> DeviceParameter { get; } = new List<DeviceParameter>();

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual ICollection<MappingWorkplaceDevice> MappingWorkplaceDevice { get; } = new List<MappingWorkplaceDevice>();
}