// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Location
{
    public long Id { get; set; }

    public string Name { get; set; } = null!;

    public string Shortname { get; set; } = null!;

    public string Name1 { get; set; } = null!;

    public string Name2 { get; set; } = null!;

    public string Street { get; set; } = null!;

    public string Housenumber { get; set; } = null!;

    public string Postcode { get; set; } = null!;

    public string Location1 { get; set; } = null!;

    public string Phone { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<BasicType> BasicType { get; set; } = new List<BasicType>();

    public virtual ICollection<Carrier> Carrier { get; set; } = new List<Carrier>();

    public virtual ICollection<ConfigMessage> ConfigMessage { get; set; } = new List<ConfigMessage>();

    public virtual ICollection<Contingent> Contingent { get; set; } = new List<Contingent>();

    public virtual ICollection<CustomerAgreement> CustomerAgreement { get; set; } = new List<CustomerAgreement>();

    public virtual ICollection<Device> Device { get; set; } = new List<Device>();

    public virtual ICollection<EventMessage> EventMessage { get; set; } = new List<EventMessage>();

    public virtual ICollection<LoadingPoint> LoadingPoint { get; set; } = new List<LoadingPoint>();

    public virtual ICollection<LocationParameter> LocationParameter { get; set; } = new List<LocationParameter>();

    public virtual ICollection<Plant> Plant { get; set; } = new List<Plant>();

    public virtual ICollection<Silo> Silo { get; set; } = new List<Silo>();

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();

    public virtual ICollection<Workplace> Workplace { get; set; } = new List<Workplace>();
}