// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Material
{
    public long Id { get; set; }

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? TradeName { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long IdUnit { get; set; }

    public string Language { get; set; } = null!;

    public bool? PrintMark { get; set; }

    public string MaterialKind { get; set; } = null!;

    public string GroupKey { get; set; } = null!;

    public virtual ICollection<BasicType> BasicType { get; set; } = new List<BasicType>();

    public virtual ICollection<ConfigPlantMaterial> ConfigPlantMaterial { get; set; } = new List<ConfigPlantMaterial>();

    public virtual ICollection<Contingent> Contingent { get; set; } = new List<Contingent>();

    public virtual ICollection<CustomerAgreement> CustomerAgreement { get; set; } = new List<CustomerAgreement>();

    public virtual Unit IdUnitNavigation { get; set; } = null!;

    public virtual ICollection<MappingMaterialTypcla> MappingMaterialTypcla { get; set; } = new List<MappingMaterialTypcla>();

    public virtual ICollection<QuantityUnit> QuantityUnit { get; set; } = new List<QuantityUnit>();
}