// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class OrderPositionText
{
    public long Id { get; set; }

    public string? Content { get; set; }

    public long IdOrderPosition { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long IdTypeOrderPositionText { get; set; }

    public virtual TypeOrderPositionText IdTypeOrderPositionTextNavigation { get; set; } = null!;
}