// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class OrderText
{
    public long Id { get; set; }

    public long IdOrder { get; set; }

    public string? Content { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long IdTypeOrderText { get; set; }

    public virtual OrderHead IdOrderNavigation { get; set; } = null!;

    public virtual TypeOrderText IdTypeOrderTextNavigation { get; set; } = null!;
}