// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Plant
{
    public long Id { get; set; }

    public long IdLocation { get; set; }

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string ShortName { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public long DeliveryNumberMin { get; set; }

    public long DeliveryNumberMax { get; set; }

    public long DeliveryNumberCurrent { get; set; }

    public long NonSapOrderMin { get; set; }

    public long NonSapOrderMax { get; set; }

    public long NonSapOrderCurrent { get; set; }

    public virtual ICollection<ConfigPlantMaterial> ConfigPlantMaterial { get; set; } = new List<ConfigPlantMaterial>();

    public virtual ICollection<ConfigPlantSalesOrg> ConfigPlantSalesOrg { get; set; } = new List<ConfigPlantSalesOrg>();

    public virtual ICollection<ConfigProductgroup> ConfigProductgroup { get; set; } = new List<ConfigProductgroup>();

    public virtual ICollection<ConfigSeal> ConfigSeal { get; set; } = new List<ConfigSeal>();

    public virtual ICollection<CustomerAgreement> CustomerAgreement { get; set; } = new List<CustomerAgreement>();

    public virtual ICollection<DeliveryOrder> DeliveryOrder { get; set; } = new List<DeliveryOrder>();

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual ICollection<LocationParameter> LocationParameter { get; set; } = new List<LocationParameter>();

    public virtual ICollection<OdcAdjustmentDay> OdcAdjustmentDay { get; set; } = new List<OdcAdjustmentDay>();

    public virtual ICollection<OrderHead> OrderHead { get; set; } = new List<OrderHead>();
}