// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Productgroup
{
    public long Id { get; set; }

    public string Name { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<ConfigPlantMaterial> ConfigPlantMaterial { get; set; } = new List<ConfigPlantMaterial>();

    public virtual ICollection<ConfigProductgroup> ConfigProductgroup { get; set; } = new List<ConfigProductgroup>();

    public virtual ICollection<DeliveryOrderPosition> DeliveryOrderPosition { get; set; } = new List<DeliveryOrderPosition>();

    public virtual ICollection<OrderPosition> OrderPosition { get; set; } = new List<OrderPosition>();
}