// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class SalesOrganization
{
    public long Id { get; set; }

    public string Vkorg { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public virtual ICollection<ConfigPlantSalesOrg> ConfigPlantSalesOrg { get; set; } = new List<ConfigPlantSalesOrg>();

    public virtual ICollection<DeliveryOrder> DeliveryOrder { get; set; } = new List<DeliveryOrder>();

    public virtual ICollection<MappingSoDebitor> MappingSoDebitor { get; set; } = new List<MappingSoDebitor>();

    public virtual ICollection<OrderHead> OrderHead { get; set; } = new List<OrderHead>();
}