// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class TypeApplicationOptionKey
{
    public long Id { get; set; }

    public long IdGroup { get; set; }

    public string KeyName { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public string InitialValue { get; set; } = null!;

    public int Datatype { get; set; }

    public virtual TypeApplicationOptionGroup IdGroupNavigation { get; set; } = null!;

    public virtual ICollection<LocationParameter> LocationParameter { get; set; } = new List<LocationParameter>();
}