// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VAgrCategoryOption
{
    public string CategoryCode { get; set; } = null!;

    public string OptionCode { get; set; } = null!;

    public long Id { get; set; }

    public long IdCategory { get; set; }

    public long IdOption { get; set; }

    public string CreateUser { get; set; } = null!;
}