// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VAuditChanges
{
    public long Id { get; set; }

    public DateTime Starttime { get; set; }

    public string Changeuser { get; set; } = null!;

    public string? Hostname { get; set; }

    public string? TableName { get; set; }

    public long IdEntity { get; set; }

    public string Op { get; set; } = null!;

    public string? Columns { get; set; }
}