// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VBasicType
{
    public long Id { get; set; }

    public string MatCode { get; set; } = null!;

    public string LocShortname { get; set; } = null!;

    public string? SpsCode { get; set; }

    public bool MixedFlag { get; set; }

    public long IdLocation { get; set; }

    public long IdMaterial { get; set; }
}