// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VContingent
{
    public long Id { get; set; }

    public long? DebNo { get; set; }

    public string Code { get; set; } = null!;

    public string? Name { get; set; }

    public int Point { get; set; }

    public bool Active { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public bool ChkLevel { get; set; }

    public bool ChkLock { get; set; }

    public string? Siloset0 { get; set; }

    public string? Siloset1 { get; set; }

    public string? Siloset2 { get; set; }

    public long IdLocation { get; set; }

    public long IdLoadingPoint { get; set; }

    public long? IdDebitor { get; set; }

    public long IdMaterial { get; set; }
}