// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VContingentSiloset
{
    public long Id { get; set; }

    public string Loc { get; set; } = null!;

    public long? DebNo { get; set; }

    public string Code { get; set; } = null!;

    public string? Name { get; set; }

    public int Point { get; set; }

    public int SiloSet { get; set; }

    public int? Silo1 { get; set; }

    public decimal? Pct1 { get; set; }

    public int? Silo2 { get; set; }

    public decimal? Pct2 { get; set; }

    public int? Silo3 { get; set; }

    public decimal? Pct3 { get; set; }

    public bool Active { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public bool ChkLevel { get; set; }

    public bool ChkLock { get; set; }

    public long IdLocation { get; set; }

    public long IdLoadingPoint { get; set; }

    public long? IdDebitor { get; set; }

    public long IdMaterial { get; set; }
}