// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VConfigProductgroup
{
    public string PlaCode { get; set; } = null!;

    public string GroupKey { get; set; } = null!;

    public string MaterialKind { get; set; } = null!;

    public string ProName { get; set; } = null!;

    public long Id { get; set; }

    public long IdPlant { get; set; }

    public long IdProductgroup { get; set; }
}