// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VCustomerAgrParameter
{
    public long Id { get; set; }

    public long? DebNo { get; set; }

    public string? Code { get; set; }

    public string CategoryCode { get; set; } = null!;

    public string OptionCode { get; set; } = null!;

    public string Value { get; set; } = null!;

    public int Datatype { get; set; }

    public string DefaultValue { get; set; } = null!;

    public long IdAgreement { get; set; }

    public long IdCategory { get; set; }

    public long IdOption { get; set; }
}