// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VDeliveryposition
{
    public long DeliveryNumber { get; set; }

    public int? PositionNumber { get; set; }

    public decimal? LoadedQuantity { get; set; }

    public string MaterialShortName { get; set; } = null!;

    public string MaterialLongName { get; set; } = null!;

    public string? CustomerProductName { get; set; }

    public string? Unit { get; set; }
}