// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VDeliveryHeadMd
{
    public long Id { get; set; }

    public long DelNo { get; set; }

    public DateTime LoadDate { get; set; }

    public string? DelState { get; set; }

    public string? SapState { get; set; }

    public long OrderNo { get; set; }

    public string Pla { get; set; } = null!;

    public string? Materialcodes { get; set; }

    public long? Deb0No { get; set; }

    public long? Deb2No { get; set; }

    public long? TransNo { get; set; }

    public string? VehicleNumber { get; set; }

    public string Art { get; set; } = null!;

    public string Deb0Name1 { get; set; } = null!;

    public string? Deb0Town { get; set; }

    public string? Device { get; set; }

    public decimal? Tara { get; set; }

    public decimal? Gross { get; set; }

    public decimal? Net { get; set; }

    public int Unit { get; set; }

    public bool NonSap { get; set; }

    public DateTime? DesiredDate { get; set; }

    public long? SlipNo { get; set; }

    public string? RailTerminal { get; set; }

    public string? ContainerNumber { get; set; }

    public decimal? Moist { get; set; }

    public string? Ident { get; set; }

    public int Cum { get; set; }

    public long? CollectNo { get; set; }

    public string Loc { get; set; } = null!;

    public long? Deb1No { get; set; }

    public long? Deb0Id { get; set; }

    public long? Deb1Id { get; set; }

    public long? Deb2Id { get; set; }
}