// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VMapSiloLoadpoint
{
    public int LoadingNumber { get; set; }

    public int SiloNumber { get; set; }

    public int Priority { get; set; }

    public string? Akz { get; set; }

    public string? SpsCode { get; set; }

    public string? SpsBasicType { get; set; }

    public string? BasicTypeCode { get; set; }

    public bool LockRail { get; set; }

    public bool LockTruck { get; set; }

    public long IdLocation { get; set; }

    public long? IdBasicType { get; set; }

    public long IdSilo { get; set; }

    public long IdLoadingPoint { get; set; }
}