// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VMaterial
{
    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string UniCode { get; set; } = null!;

    public string UniName { get; set; } = null!;

    public string MaterialKind { get; set; } = null!;

    public string GroupKey { get; set; } = null!;

    public bool PrintMark { get; set; }

    public string Language { get; set; } = null!;

    public string? TradeName { get; set; }

    public long Id { get; set; }

    public long IdUnit { get; set; }
}