// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VSilo
{
    public long Id { get; set; }

    public int Num { get; set; }

    public string Name { get; set; } = null!;

    public bool Dry { get; set; }

    public string? Points { get; set; }

    public int Prio { get; set; }

    public string? Akz { get; set; }

    public string? SpsCode { get; set; }

    public string? SpsType { get; set; }

    public string? BasicCode { get; set; }

    public string? Add1Code { get; set; }

    public string? Add2Code { get; set; }

    public string? Add3Code { get; set; }

    public bool LockRail { get; set; }

    public bool LockTruck { get; set; }

    public bool LockBigbag { get; set; }

    public bool LockForProduction { get; set; }

    public bool LockLaboratory { get; set; }

    public bool LockForSensitiveCustomer { get; set; }

    public int SortNumber { get; set; }

    public decimal? MaxPercentage { get; set; }

    public decimal? SiloVolume { get; set; }

    public decimal? SiloLevelVolume { get; set; }

    public decimal? SiloLevelPercentage { get; set; }

    public decimal? MinSiloLevelVolume { get; set; }

    public string? DrainageTime { get; set; }

    public long IdLocation { get; set; }

    public long? IdBasicType { get; set; }
}