// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class VSiloMatrix
{
    public string? SiloName { get; set; }

    public string? SpsBasicType { get; set; }

    public string? MaterialCode { get; set; }

    public string? MaterialName { get; set; }

    public decimal? SiloLevelVolume { get; set; }

    public string? DrainageTime { get; set; }

    public bool? LockTruck { get; set; }

    public bool? LockRail { get; set; }

    public bool? LockForProduction { get; set; }

    public bool? LockLaboratory { get; set; }

    public bool? LockForSensitiveCustomer { get; set; }

    public bool? Dry { get; set; }

    public int? Priority { get; set; }

    public long? Id { get; set; }

    public string? Kind { get; set; }

    public int? SortNumber { get; set; }
}