// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Quva.Database.Models;

public partial class Workplace
{
    public long Id { get; set; }

    public string Name { get; set; } = null!;

    public long IdLocation { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? ChangeUser { get; set; }

    public DateTime? ChangeDate { get; set; }

    public int ChangeNumber { get; set; }

    public string? Note { get; set; }

    public virtual Location IdLocationNavigation { get; set; } = null!;

    public virtual ICollection<MappingUserWorkplace> MappingUserWorkplace { get; set; } = new List<MappingUserWorkplace>();

    public virtual ICollection<MappingWorkplaceDevice> MappingWorkplaceDevice { get; set; } = new List<MappingWorkplaceDevice>();

    public virtual ICollection<Printer> Printer { get; set; } = new List<Printer>();

    public virtual ICollection<WorkplaceParameter> WorkplaceParameter { get; set; } = new List<WorkplaceParameter>();
}