// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeviceSimulator.Models
{
    public partial class Device
    {
        public Device()
        {
            DeviceParameter = new HashSet<DeviceParameter>();
        }

        public long Id { get; set; }
        public long? IdLocation { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ModuleCode { get; set; }
        public long? PackagingType { get; set; }
        public long? TransportType { get; set; }
        public string Paramstring { get; set; }
        public long? DeviceType { get; set; }
        public long? Porttype { get; set; }
        public string CreateUser { get; set; }
        public string CreateDate { get; set; }
        public string ChangeUser { get; set; }
        public string ChangeDate { get; set; }
        public long? ChangeNumber { get; set; }
        public string Note { get; set; }
        public long? Roles { get; set; }

        public virtual ICollection<DeviceParameter> DeviceParameter { get; set; }
    }
}